# Generated by Django 4.2.11 on 2024-03-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicksense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubemodel',
            name='json_data',
            field=models.TextField(default='{}'),
        ),
    ]
