class Constants():
    FREE_PLAN = "FREEPLAN"
    FREE_PLAN_CREDIT = 100
    MONTHLY_PLAN = "MONTHLYPLAN"
    MONTHLY_PLAN_CREDIT = 500
    YEARLY_PLAN = "YEARLYPLAN"
    YEARLY_PLAN_CREDIT = 1000
    EMPTY_JSON = {}
